# Generated by Django 2.0.2 on 2018-10-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField()),
                ('character_name', models.CharField(max_length=255)),
                ('smash_tag', models.CharField(max_length=255)),
                ('video_titel', models.CharField(max_length=255)),
            ],
        ),
    ]
