# Generated by Django 2.0.2 on 2018-10-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='iframe_url',
            field=models.CharField(default='https://www.youtube.com/embed/99MZ4hp4L9E?start=229&end235', max_length=255),
            preserve_default=False,
        ),
    ]
